### ISSUE TITLE
SSL cert validation

### ISSUE THREAD

**Issue by ifduyue** [ifduyue/urlfetch#37]

**Comment by iAmAnkeeta** [comment]
Any update on when this will be implemented?

I am using `urlfetch.request()` and I am getting the error below
```
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)
```

**Comment by ifduyue** [comment]
@iAmAnkeeta What your OS version and Python version?

**Comment by iAmAnkeeta** [comment]
OS: MacOS Mojave
Python: 3.7.4

**Comment by ifduyue** [comment]
What's the output of `ssl.get_default_verify_paths()`

**Comment by ifduyue** [comment]
![image](https://user-images.githubusercontent.com/568900/61482623-a994c580-a9cd-11e9-91b9-55cd2de7a5be.png)

Did you installed Python 3.7.4 from python.org installer? If true, try this `open /Applications/Python\ 3.7/Install\ Certificates.command`
