### ISSUE TITLE
tests depend on bottle app tests/server.py running on localhost

### ISSUE THREAD

**Issue by jayvdb** [ifduyue/urlfetch#39]
python setup.py test fails badly for me on py2.7.

The tests depend on the bottle app in tests/server.py to act as the server, and the tests.testall test target in setup.py isnt working correctly.

Firstly, setup.py should list bottle as a test dependency.

To assist, the following would also be useful:

* some documentation to run the tests,
* a .travis.yml as a sample on how to run the tests,

The following does not work for me, unless urlfetch is already installed or PYTHONPATH is changed.

```python
$ python tests/testall.py
Traceback (most recent call last):
  File "tests/testall.py", line 21, in <module>
    suite = unittest.defaultTestLoader.loadTestsFromNames(tests)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "/tmp/urlfetch/tests/test_others.py", line 2, in <module>
    import urlfetch
ImportError: No module named urlfetch
```
If I manually start the server, the tests pass.

**Comment by ifduyue** [comment]
Thanks for the report. You're right.

**Comment by ifduyue** [comment]
Still working on this.

**Comment by ifduyue** [comment]
@jayvdb please check if this is fixed.

**Comment by jayvdb** [comment]
Lovely.  ' setup.py test ' works out of the box now, without being installed first.

Could you drop a note in one of these issues when you've released a new version, so I can remove the custom repo from https://github.com/jayvdb/anyhttp/blob/master/setup.py#L46 , so setuptools can pull the new version from https://pypi.python.org/simple/urlfetch/.

**Comment by ifduyue** [comment]
@jayvdb OK, I'll push a new release

**Comment by ifduyue** [comment]
@jayvdb done. https://pypi.python.org/pypi/urlfetch/1.0.2
