### ISSUE TITLE
_ssl.c:510: EOF occurred in violation of protocol

### ISSUE THREAD

**Issue by kongakong** [ifduyue/urlfetch#41]
It starts to occur when the target server 's ssl cert has been updated. 

A lot of similar issues have been lodged for another project `request`. The solution was mostly 

      pip install --force-reinstall requests[security]

to update some dependencies

However when I run it I got:

       requests 2.2.1 does not provide the extra 'security'

Any other suggestion?

**Comment by kongakong** [comment]
I have provided more info in this SO post http://stackoverflow.com/questions/44037972/urlfetch-urlfetchexception-ssl-c510-eof-occurred-in-violation-of-protocol

**Comment by ifduyue** [comment]
@kongakong Hello

What is the Python version you're using?
urlfetch itself is a wrapper of python std lib (httplib in python2, http.client in python3), if you're using python2 you might want to use a rencent version which is greater than 2.7.9
